export const stackedBarChartSeries: any[] = [
  {
    type: "bar",
    xKey: "Month",
    yKey: "Lexus",
    yName: "Lexus",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Volkswagen",
    yName: "Volkswagen",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Acura",
    yName: "Acura",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Alfa Romeo",
    yName: "Alfa Romeo",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "AMC",
    yName: "AMC",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Audi",
    yName: "Audi",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Bertone",
    yName: "Bertone",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "BMW",
    yName: "BMW",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Buick",
    yName: "Buick",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Cadillac",
    yName: "Cadillac",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Chevrolet",
    yName: "Chevrolet",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Chrysler",
    yName: "Chrysler",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Daewoo",
    yName: "Daewoo",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Daihatsu",
    yName: "Daihatsu",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Dodge",
    yName: "Dodge",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Eagle",
    yName: "Eagle",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Ford",
    yName: "Ford",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Geo",
    yName: "Geo",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "GMC",
    yName: "GMC",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Honda",
    yName: "Honda",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Hummer",
    yName: "Hummer",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Hyundai",
    yName: "Hyundai",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Infiniti",
    yName: "Infiniti",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Isuzu",
    yName: "Isuzu",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Jaguar",
    yName: "Jaguar",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Jeep",
    yName: "Jeep",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Kia",
    yName: "Kia",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Land Rover",
    yName: "Land Rover",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Lincoln",
    yName: "Lincoln",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Mazda",
    yName: "Mazda",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Mercedes-Benz",
    yName: "Mercedes-Benz",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Mercury",
    yName: "Mercury",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Merkur",
    yName: "Merkur",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "MINI",
    yName: "MINI",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Mitsubishi",
    yName: "Mitsubishi",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Nissan",
    yName: "Nissan",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Oldsmobile",
    yName: "Oldsmobile",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Peugeot",
    yName: "Peugeot",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Pininfarina",
    yName: "Pininfarina",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Plymouth",
    yName: "Plymouth",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Pontiac",
    yName: "Pontiac",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Porsche",
    yName: "Porsche",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Renault",
    yName: "Renault",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Saab",
    yName: "Saab",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Saa",
    yName: "Saa",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Saturn",
    yName: "Saturn",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Sterling",
    yName: "Sterling",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Subaru",
    yName: "Subaru",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Suzuki",
    yName: "Suzuki",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Toyota",
    yName: "Toyota",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Volvo",
    yName: "Volvo",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Yugo",
    yName: "Yugo",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Fiat",
    yName: "Fiat",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Smart",
    yName: "Smart",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "SCION",
    yName: "SCION",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "MAHER",
    yName: "MAHER",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "TESLA",
    yName: "TESLA",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "Test make",
    yName: "Test make",
    stacked: true,
    normalizedTo: 100,
  },
  {
    type: "bar",
    xKey: "Month",
    yKey: "RAM",
    yName: "RAM",
    stacked: true,
    normalizedTo: 100,
  },
];
